// Demo mode — fake data for testing UI without Convex auth
export const DEMO_MODE = true;

export const DEMO_USER = {
  _id: "demo_user_1" as any,
  _creationTime: 1713100800000,
  name: "Maître Dupont",
  email: "dupont@lexicab.fr",
  role: "associe" as const,
  isActive: true,
};

export const DEMO_USERS = [
  DEMO_USER,
  {
    _id: "demo_user_2" as any,
    _creationTime: 1713100800000,
    name: "Sophie Martin",
    email: "martin@lexicab.fr",
    role: "collaborateur" as const,
    isActive: true,
  },
  {
    _id: "demo_user_3" as any,
    _creationTime: 1713100800000,
    name: "Julie Lefebvre",
    email: "lefebvre@lexicab.fr",
    role: "secretaire" as const,
    isActive: true,
  },
  {
    _id: "demo_user_4" as any,
    _creationTime: 1713100800000,
    name: "Paul Renard",
    email: "renard@lexicab.fr",
    role: "stagiaire" as const,
    isActive: true,
  },
];

export const DEMO_CLIENTS = [
  {
    _id: "demo_client_1" as any,
    _creationTime: 1713100800000,
    type: "personne_morale" as const,
    denomination: "TechVision SAS",
    formeJuridique: "SAS",
    siren: "123456789",
    siret: "12345678900001",
    siegeSocial: "42 avenue des Champs-Élysées, 75008 Paris",
    capitalSocial: "500 000 €",
    dirigeants: "Jean-Marc Dubois (Président)",
    secteurActivite: "Technologies",
    dateCreation: "2018-03-15",
    avocatReferentId: "demo_user_1" as any,
    tags: ["VIP", "groupe"],
    notes: "Client stratégique depuis 2020",
    specialites: ["corporate" as const, "fiscal" as const],
    isActive: true,
  },
  {
    _id: "demo_client_2" as any,
    _creationTime: 1713100800000,
    type: "personne_morale" as const,
    denomination: "Immobilière du Parc SARL",
    formeJuridique: "SARL",
    siren: "987654321",
    siegeSocial: "15 rue de la Paix, 75002 Paris",
    capitalSocial: "200 000 €",
    dirigeants: "Marie Fontaine (Gérante)",
    secteurActivite: "Immobilier",
    dateCreation: "2010-06-22",
    avocatReferentId: "demo_user_2" as any,
    tags: ["client sensible"],
    specialites: ["litige" as const, "corporate" as const],
    isActive: true,
  },
  {
    _id: "demo_client_3" as any,
    _creationTime: 1713100800000,
    type: "personne_morale" as const,
    denomination: "Groupe Mercier SA",
    formeJuridique: "SA",
    siren: "456789123",
    siegeSocial: "8 boulevard Haussmann, 75009 Paris",
    capitalSocial: "2 000 000 €",
    dirigeants: "Philippe Mercier (PDG)",
    secteurActivite: "Commerce",
    dateCreation: "1995-01-10",
    avocatReferentId: "demo_user_1" as any,
    tags: ["VIP"],
    specialites: ["fiscal" as const],
    isActive: true,
  },
  {
    _id: "demo_client_4" as any,
    _creationTime: 1713100800000,
    type: "personne_physique" as const,
    denomination: "Laurent Bertrand",
    prenom: "Laurent",
    nom: "Bertrand",
    siegeSocial: "25 rue du Faubourg Saint-Honoré, 75008 Paris",
    avocatReferentId: "demo_user_2" as any,
    specialites: ["litige" as const],
    isActive: true,
  },
];

export const DEMO_DOSSIERS = [
  {
    _id: "demo_dossier_1" as any,
    _creationTime: 1713100800000,
    reference: "COR-2026-0001",
    clientId: "demo_client_1" as any,
    specialite: "corporate" as const,
    intitule: "Constitution filiale TechVision Cloud",
    description: "Création d'une SAS filiale pour l'activité cloud computing",
    statut: "en_cours_redaction",
    avocatResponsableId: "demo_user_1" as any,
    collaborateursIds: ["demo_user_2" as any],
    montantHonoraires: 15000,
    dateOuverture: "2026-03-01",
    partiesAdverses: [],
  },
  {
    _id: "demo_dossier_2" as any,
    _creationTime: 1713100800000,
    reference: "LIT-2026-0003",
    clientId: "demo_client_2" as any,
    specialite: "litige" as const,
    intitule: "Litige commercial vs. BTP Constructions",
    description: "Inexécution contrat de rénovation — demande en paiement 450 000 €",
    statut: "contentieux_en_cours",
    avocatResponsableId: "demo_user_2" as any,
    collaborateursIds: ["demo_user_1" as any, "demo_user_4" as any],
    montantHonoraires: 25000,
    dateOuverture: "2026-01-15",
    partiesAdverses: [{ denomination: "BTP Constructions SARL", siren: "111222333", avocat: "Me Rousseau" }],
  },
  {
    _id: "demo_dossier_3" as any,
    _creationTime: 1713100800000,
    reference: "FIS-2026-0002",
    clientId: "demo_client_3" as any,
    specialite: "fiscal" as const,
    intitule: "Restructuration fiscale Groupe Mercier",
    description: "Optimisation IS via holding — intégration fiscale",
    statut: "en_cours_analyse",
    avocatResponsableId: "demo_user_1" as any,
    collaborateursIds: [],
    montantHonoraires: 35000,
    dateOuverture: "2026-02-10",
    partiesAdverses: [],
  },
  {
    _id: "demo_dossier_4" as any,
    _creationTime: 1713100800000,
    reference: "LIT-2026-0007",
    clientId: "demo_client_4" as any,
    specialite: "litige" as const,
    intitule: "Recouvrement créance Bertrand / SCI Étoile",
    description: "Injonction de payer — loyers impayés",
    statut: "phase_amiable",
    avocatResponsableId: "demo_user_2" as any,
    collaborateursIds: ["demo_user_4" as any],
    montantHonoraires: 5000,
    dateOuverture: "2026-03-20",
    partiesAdverses: [{ denomination: "SCI Étoile du Nord" }],
  },
];

const today = new Date();
const inDays = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString().split("T")[0];
};

export const DEMO_ECHEANCES = [
  {
    _id: "demo_ech_1" as any,
    _creationTime: 1713100800000,
    dossierId: "demo_dossier_1" as any,
    description: "Dépôt des statuts au greffe",
    date: inDays(2),
    responsableId: "demo_user_1" as any,
    statut: "a_venir" as const,
    type: "administrative" as const,
  },
  {
    _id: "demo_ech_2" as any,
    _creationTime: 1713100800000,
    dossierId: "demo_dossier_2" as any,
    description: "Dépôt conclusions récapitulatives",
    date: inDays(1),
    responsableId: "demo_user_2" as any,
    statut: "a_venir" as const,
    type: "procedurale" as const,
  },
  {
    _id: "demo_ech_3" as any,
    _creationTime: 1713100800000,
    dossierId: "demo_dossier_3" as any,
    description: "Date limite déclaration IS",
    date: inDays(5),
    responsableId: "demo_user_1" as any,
    statut: "a_venir" as const,
    type: "fiscale" as const,
  },
  {
    _id: "demo_ech_4" as any,
    _creationTime: 1713100800000,
    dossierId: "demo_dossier_2" as any,
    description: "Audience de plaidoirie — TC Paris",
    date: inDays(14),
    responsableId: "demo_user_2" as any,
    statut: "a_venir" as const,
    type: "procedurale" as const,
  },
  {
    _id: "demo_ech_5" as any,
    _creationTime: 1713100800000,
    dossierId: "demo_dossier_4" as any,
    description: "Envoi mise en demeure",
    date: inDays(-1),
    responsableId: "demo_user_2" as any,
    statut: "en_retard" as const,
    type: "procedurale" as const,
  },
];

export const DEMO_FACTURE_STATS = {
  emis: 75000,
  encaisse: 45000,
  impaye: 12500,
  tauxRecouvrement: 78,
  totalMois: 75000,
  facturesAEmettre: 3,
  relancesEnCours: 2,
};

export const DEMO_FACTURES = [
  {
    _id: "demo_fac_1" as any,
    _creationTime: 1713100800000,
    dossierId: "demo_dossier_1" as any,
    clientId: "demo_client_1" as any,
    numero: "FAC-2026-0001",
    description: "Honoraires constitution filiale — Acompte",
    montantHT: 5000,
    tva: 1000,
    montantTTC: 6000,
    statut: "payee" as const,
    dateEmission: "2026-03-05",
    dateEcheance: "2026-04-05",
    datePaiement: "2026-03-28",
    createdBy: "demo_user_3" as any,
    valideeBy: "demo_user_1" as any,
  },
  {
    _id: "demo_fac_2" as any,
    _creationTime: 1713100800000,
    dossierId: "demo_dossier_2" as any,
    clientId: "demo_client_2" as any,
    numero: "FAC-2026-0002",
    description: "Honoraires litige BTP — Phase contentieuse",
    montantHT: 12500,
    tva: 2500,
    montantTTC: 15000,
    statut: "envoyee" as const,
    dateEmission: "2026-03-15",
    dateEcheance: "2026-04-15",
    createdBy: "demo_user_3" as any,
  },
  {
    _id: "demo_fac_3" as any,
    _creationTime: 1713100800000,
    dossierId: "demo_dossier_3" as any,
    clientId: "demo_client_3" as any,
    numero: "FAC-2026-0003",
    description: "Honoraires restructuration fiscale",
    montantHT: 10000,
    tva: 2000,
    montantTTC: 12000,
    statut: "en_retard" as const,
    dateEmission: "2026-02-15",
    dateEcheance: "2026-03-15",
    createdBy: "demo_user_3" as any,
    valideeBy: "demo_user_1" as any,
  },
];

export const DEMO_ACTIVITES = [
  {
    _id: "demo_act_1" as any,
    _creationTime: 1713100800000 - 1000 * 60 * 30,
    dossierId: "demo_dossier_1" as any,
    clientId: "demo_client_1" as any,
    utilisateurId: "demo_user_1" as any,
    type: "document_ajoute",
    description: "Statuts SAS TechVision Cloud v3 ajoutés",
  },
  {
    _id: "demo_act_2" as any,
    _creationTime: 1713100800000 - 1000 * 60 * 120,
    dossierId: "demo_dossier_2" as any,
    clientId: "demo_client_2" as any,
    utilisateurId: "demo_user_2" as any,
    type: "statut_change",
    description: 'Statut changé de "pré-contentieux" à "contentieux en cours"',
  },
  {
    _id: "demo_act_3" as any,
    _creationTime: 1713100800000 - 1000 * 60 * 60 * 5,
    clientId: "demo_client_3" as any,
    utilisateurId: "demo_user_1" as any,
    type: "facture_emise",
    description: "Facture FAC-2026-0003 émise — 12 000 € TTC",
  },
  {
    _id: "demo_act_4" as any,
    _creationTime: 1713100800000 - 1000 * 60 * 60 * 24,
    dossierId: "demo_dossier_3" as any,
    utilisateurId: "demo_user_1" as any,
    type: "dossier_cree",
    description: "Dossier FIS-2026-0002 créé : Restructuration fiscale Groupe Mercier",
  },
];

export const DEMO_DOSSIER_COUNT = {
  total: 4,
  corporate: 1,
  litige: 2,
  fiscal: 1,
  actifs: 4,
};
